name: paused_secret
description: paused secret.
version: 0.0.2

homepage: https://github.com/jawa0919/paused_secret
repository: https://github.com/jawa0919/paused_secret
issue_tracker: https://github.com/jawa0919/paused_secret/issues

screenshots:
  - description: "Examples is runing android"
    path: docs/img/and.png
  - description: "Examples is runing ios"
    path: docs/img/ios.png

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: top.jawa0919.paused_secret
        pluginClass: PausedSecretPlugin
      ios:
        pluginClass: PausedSecretPlugin
